### ISSUE TITLE
Possibly ExtractRelativeDataPath can be removed, and the work done in more portable way

### ISSUE THREAD

**Issue by michaliskambi** [Kagamma/cge-3d-particle-emitter#4]
`ExtractRelativeDataPath` inside `demos/editor/gamestatemain.pas` does URL processing, assuming it is a `file:` URL.

Possibly it can be done cleaner (in a way that accounts that in URL some chars may be encoded), and in a way that for sure works on all platforms.

Do you want to just convert URL to a filename? Because I see `ExtractRelativeDataPath` is used only for a call to `Effect.Save`, that seems to expect a filename, since it uses `TFileStream.Create(AURL, ...)`.

Then

1. Use `URLToFilenameSafe` from `CastleURIUtils`.

2. Or, even better: do nothing (just call `Effect.Save(URL)`, and remove `ExtractRelativeDataPath`) and inside `TCastle3DParticleEffect.Save` support URLs. You can just replace

    ```
    FS := TFileStream.Create(AURL, fmCreate);
    ```

    with

    ```
    S := URLSaveStream(AURL);
    ```

    (S is a now a general `TStream`) and maybe that is enough.

**Comment by Kagamma** [comment]
Thanks. I follow your suggestion and use URLSaveStream. I also fix a minor bug related to whitespaces in URL.
